reference_genome:
  /home/ec2-user/course_data/resources/reference/human_g1k_v37.fasta
workbatch:
  /home/ec2-user/NGS_pipeline
tempfolder:
  /home/ec2-user/NGS_pipeline/tmp
java:
  /usr/bin/java
picard:
  /home/ec2-user/software/picard/picard.jar
python:
  ~/miniconda3/bin/python 
known_indels:
  /home/ec2-user/course_data/resources/filtering_annotation/Mills_and_1000G_gold_standard.indels.b37.vcf
rscript:
  /usr/bin/Rscript
common:
  /home/ec2-user/course_data/resources/filtering_annotation/common_no_known_medical_impact_20160302-edited.vcf
artefacts:
  /home/ec2-user/course_data/resources/filtering_annotation/V501_19052014_common_artefacts.vcf
alamut:
  /home/ec2-user/software/alamut/alamut-batch-standalone-1.5.2/alamut-batch

samples:
  #format sample_name: [<forward_fastq>, <reverse_fastq>, <gender>, <library>, <panel>]  
  #sample_1: ["v501_EX0000001_S17_R1_001.fastq.gz", "v501_EX0000001_S17_R2_001.fastq.gz", "FEMALE", "v501", "HI"]
  sample_2: ["v501_EX000002_S17_R1_001.fastq.gz", "v501_EX000002_S17_R2_001.fastq.gz", "FEMALE", "v501", "HI"]   
