from os.path import join

configfile: "config.yaml"

include: "./samtobam"
include: "./fixmate"
include: "./markduplicates"
include: "./realignertargetcreator"
include: "./indelrealigner"
include: "./phenotypecoverage"
include: "./hsmetrics"
include: "./exomedepth"
include: "./excludeunwanted"
include: "./excludeartefacts"
include: "./alamutannotate"

fa = config["reference_genome"]
java = config["java"]
picard = config["picard"]
workbatch = config["workbatch"]
tempfolder = config["tempfolder"]
known_indels = config["known_indels"]
rscript = config["rscript"]
alamut = config["alamut"]
python=config["python"]
samples=config["samples"]

rule all:
    input:
        #expand("{workbatch}/variants/{sample}_annotated.txt", workbatch=workbatch, sample=samples),
        #expand("{workbatch}/metrics/phenotypecoverage/{sample}_phenotypecoverage", workbatch=workbatch, sample=samples),
        #expand("{workbatch}/metrics/hsmetrics/{sample}_hsmetrics", workbatch=workbatch, sample=samples)

